### ISSUE TITLE
How to handle receiving messages in large sizes?

### ISSUE THREAD

**Issue by Janecifer** [Marfusios/websocket-client#120]
Hi Marfusios,

Thanks for this great lib.
Mat I trouble you how you handle large messages? It works well in small sizes of data. But we have a situation that may receive the 10M data, then it will throw an Exception. 
 _[ERR] [WEBSOCKET CLIENT] Error while listening to websocket stream, error: 'An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.'
System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, String errorMessage, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
--- End of stack trace from previous location ---
   at Websocket.Client.WebsocketClient.Listen(WebSocket client, CancellationToken token)_

We try to add an option for increasing the buffer size, but it didn't help. _ _clientFactory.Options.SetBuffer(20971520, 10240);_

Thanks for help!

**Comment by Marfusios** [comment]
Hey @Janecifer , 
what is the `InnerException`?

**Comment by m17kea** [comment]
I have the same issue, the inner exception is null. The exception I have is: 
```
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, String errorMessage, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
--- End of stack trace from previous location ---
   at Websocket.Client.WebsocketClient.Listen(WebSocket client, CancellationToken token)
```

**Comment by zhiming0228** [comment]
I have the same issue, [client.Options.SetBuffer(40960, 40960);]  it didn't work. I don't know where the sendBufferSize field work. Is there any way to modify the send or receive buffer size?
